# syntax=docker/dockerfile:1

FROM golang:1.19

RUN mkdir -p '/usr/src/app'

WORKDIR /usr/src/app

COPY *.go ./

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod go.sum ./

RUN go mod download && go mod verify

RUN go build -v -o /usr/local/bin/app

EXPOSE 8080

CMD ["app", "serve", "--http=0.0.0.0:8880", "--origins=*"]